env:
  global:
    secure: bMkuB4hgv7IpZUFg2tL77NP3ea+jv0v/VrioLEY1DP3CCGmpleDI5mIcmBBMlkhXPS5fRDg+SgrVY7rYrPHXbuvvG28yvN2CjNFsUx0V5CjxYoKebP8XInJfXM1nq//kAZi7K04VVy002Q40uFqqojLCr6msB2yG2ra+wkeT0z9oKx5BneL/UAtaRCxvmrYV5hq9LADhi7dyJ8lrmnZmaNi7O2gzGbV8VZEH+7meiPxPGtXhVFDWXa7S9By1hq/DteN5wnrD73METlpzvmCMEH+rtBWHT3a7suHjaPL77+gqfSUq8VMdSwQnpJjsJvPfAN/rl66TIW6zRPc37IM2zJKWSSTj7Sn5rhdYr5cVA4YU7lUUEUWXm/+A29v5cMBVAi7/sZ4Ud2TaawAScg/xv9+wTr7EeRk7HL0Oy0uQQjBd7qP+4NASwWh9/EpNciII7Zjnf9yjESjJtjjrFRaT6+VlVmzRZ4FdlaieDTwwjXYg+yFy5MtBpunSZym/8AgBSjLLwvrjooKImf2gzGdgwq4ixO42bwfcLj3WvtjU2VjIor1HRamoopc3t3DzU+JpsREliQQZ/SeKYlFOx4jpQIzy00e77E/qixFmTzebRP0jxqGginl5WruQXPsKQJ2mGnZde9aS958TOLdJMoBsLfEI/QuBJMHEppWEkW6bfTo=
matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '10'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: generic
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
install:
- npm install
- npm run generate-icons
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm run dist"
   else
     npm run dist
   fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
deploy:
  provider: releases
  api_key:
    secure: QeZfqVS8cbHiioYkLQmCJvA/g5eYL3l9Kzqc+ceoX5U/oyQOlZRUPJDYVjDwr8SNhYr5KHK5HnFXFSQYzEXAmsw+v5LoqUKKxqUtuUc3b8tbipa0TbjInEo+Fm2b+K/GMU+10oX5JCEtYz49pHdZzdpW23EdGf4Z0tYWt5DvSJ0AkDswhDqOVlk2I7PswwlSzooSIqkwRF819p2QU9t+tIGsArvtwHriDyyG1xUXYUNjDOnBYuxbv8tyObmhcJLcLM7xIIVPQfCfN+1vmfpc0o0BJjm/K3guRzDCYYrYYhPY5i7gHkfZm3sfBoo0QfgmEWBQ45Za2L9N1k3koLupf4bW/oBWGTtKdgPTxU138hAvLC+bm1dd2Yx8kOn+xxaK3FtVSaXivv/iR/7RfXGyHfm4yBVlOTGMdMwYx+4+n+iQ/6kbsF6u0Fr2JwzJAKWd0qkBpThRuhJdHveDRZZqvwWluYELhBdgUhdFnt6bevvQixEP3nYR8+9yiBC48sge+qWoq1VQ8ySuLa8v3BAH50F9d/c3MjnmRCAK28WlMRx9k41ZJY7kzmFxh5/3h834lMkOpen/CjVOQe3N0SJlcb+w0hmzDoUN29X3jZ0GQR1wD4rkcpHhQRcneTpMeZYoWvHJCWS65zXzopbpNe94OGRRsJJzZ7abGq1UHzkQ8jQ=
  file_glob: true
  file: dist/*.dmg
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  draft: true
  on:
    repo: moshfeu/y2mp3
    tags: true
